### ISSUE TITLE
Parsing DNS queries with EDNS OPT records that set D0 fails

### ISSUE THREAD

**Issue by siebenmann** [LinkTed/dns-message-parser#10]
If you attempt to parse a DNS query with an RFC 6891 EDNS OPT record that sets the D0 bit (DNSSEC OK), parsing will fail with the error `OPT header bits is not zero: 128` (DecodeError::OPTZero). I believe that this is because src/decode/rr/edns/rfc_6891.rs's `rr_opt_ttl()` looks at the wrong bit to determine its `dnssec` value. The current code says a 0 value in the 3rd octet of the TTL field is no, a 1 value is yes, and anything else is an error. However, RFC 6891 says that the D0 bit is the high bit of the 3rd octet, not the low bit, so I believe the three values checked for should be 0, 128, and error.

(I encountered this issue through use of @jvns's [dnspeep](https://github.com/jvns/dnspeep), which parses DNS packets using this crate.)

**Comment by LinkTed** [comment]
Thanks for the reporting. I fix the bug and wrote some tests for D0 bit parsing.
