### ISSUE TITLE
Support TXT with rdata bigger than 255 bytes

### ISSUE THREAD

**Issue by rushmorem** [LinkTed/dns-message-parser#18]
`TXT { string: String, .. }` should probably be `TXT { strings: Vec<String>, .. }` instead.

**Comment by LinkTed** [comment]
Why? According to the RFC [1035](https://datatracker.ietf.org/doc/html/rfc1035#section-3.3.14) TXT is only one string. Or did it change?

**Comment by rushmorem** [comment]
To quote that RFC:-

> TXT-DATA        One or more <character-string>s

Each string can contain upto 255 bytes but this is not enough in some cases. For example some DKIM records are longer than this so TXT allows to split big strings into chunks of upto 255 bytes. In total, TXT data can contain upto 65535 bytes (people typically limit this to a smaller size though).

https://datatracker.ietf.org/doc/html/rfc6763#section-6.1:

>    A DNS TXT record can be up to 65535 (0xFFFF) bytes long.  The total
>    length is indicated by the length given in the resource record header
>    in the DNS message.  There is no way to tell directly from the data
>    alone how long it is (e.g., there is no length count at the start, or
>    terminating NULL byte at the end).

[This Amazon article](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html#TXTformat-limits) has a bit more info on their own implementation of TXT records.

**Comment by LinkTed** [comment]
I changed it 35e8bfc7aaf48b465d300060a1bd899d41a57c6c. Thanks for your support.

**Comment by rushmorem** [comment]
Awesome! Thanks!
