### ISSUE TITLE
feature request: allow set id, flags, questions, answers, authorities and additionals

### ISSUE THREAD

**Issue by Sherlock-Holo** [LinkTed/dns-message-parser#2]
## The problems encountered

for now `Dns` only can get id, flags, and others. When the server parses the dns and want to reply client, server only can create a new `Dns` and clone the header and queries.

## solution

allow set `id`, `flags`, `questions`, `answers`, `authorities` and `additionals`.

If can set these field, server can reuse the `Dns` which is read from client, add the answers and return the `Dns` directly

**Comment by LinkTed** [comment]
Hi,
I change the visibility of the fields. Now you can change the values.
