### ISSUE TITLE
SOA RNAME does not support email addresses that contain dots

### ISSUE THREAD

**Issue by rushmorem** [LinkTed/dns-message-parser#21]
If someone uses an RNAME like `john.doe@example.com` it will be represented as `john\.doe.example.com.` in the SOA record. `DomainName` refuses to parse this saying "Label contains dot". I think `DomainName` is too restrictive here.

https://datatracker.ietf.org/doc/html/rfc2181#section-11 says:

>    Occasionally it is assumed that the Domain Name System serves only
>    the purpose of mapping Internet host names to data, and mapping
>    Internet addresses to host names.  This is not correct, the DNS is a
>    general (if somewhat limited) hierarchical database, and can store
>    almost any kind of data, for almost any purpose.
> 
>    The DNS itself places only one restriction on the particular labels
>    that can be used to identify resource records.  That one restriction
>    relates to the length of the label and the full name.  The length of
>    any one label is limited to between 1 and 63 octets.  A full domain
>    name is limited to 255 octets (including the separators).  The zero
>    length full name is defined as representing the root of the DNS tree,
>    and is typically written and displayed as ".".  Those restrictions
>    aside, any binary string whatever can be used as the label of any
>    resource record.  Similarly, any binary string can serve as the value
>    of any record that includes a domain name as some or all of its value
>    (SOA, NS, MX, PTR, CNAME, and any others that may be added).
>    Implementations of the DNS protocols must not place any restrictions
>    on the labels that can be used.  In particular, DNS servers must not
>    refuse to serve a zone because it contains labels that might not be
>    acceptable to some DNS client programs.  A DNS server may be
>    configurable to issue warnings when loading, or even to refuse to
>    load, a primary zone containing labels that might be considered
>    questionable, however this should not happen by default.

In the `addr` crate (https://github.com/addr-rs/addr/blob/3851f0868d24282f7968dcc3fc40ab1687e9aef6/src/matcher.rs#L65-L92) I only  make sure that it's not empty, has no empty labels and that the full DNS name and individual labels are within the specified length.

**Comment by LinkTed** [comment]
Thanks for the info. Yes, it seems to be too restrictive. I will change the behav.ior

**Comment by LinkTed** [comment]
The `addr` seems to have a bug: If you use `example\..org`. It will return with `EmptyLabel`.

**Comment by rushmorem** [comment]
> The `addr` seems to have a bug: If you use `example\..org`. It will return with `EmptyLabel`.

Thanks for pointing that out. Will fix it.

**Comment by rushmorem** [comment]
On second thought, should `example\..org` even be allowed? Using that `john\.doe.example.com` example, outside DNS names it translates to `john.doe@example.com` which is a valid email address while `johndoe\..example.com` translates to `johndoe.@example.com` which isn't, as far as I know.

**Comment by LinkTed** [comment]
The general problem I see here if I want to convert a `DomainName` to a `String`, how do I distinguish a dot, which is part of a label, and a dot, which is the separator? If I use a backslash to escape it, then I need also have to escape the backslash. And what should happen if someone use `\a` or `\b` (or any other character with the prefix backslash)?

**Comment by rushmorem** [comment]
How about just returning the underlying string unaltered, like we are doing now?

**Comment by LinkTed** [comment]
If you convert it to `String` and a label contains a dot, convert back to a `DomainName`, then it would be parsed differently. I will do it like how it is now (unaltered).

**Comment by LinkTed** [comment]
I change the domain name so that the label can contain dots. See fb7d3e384f4f2c2014485cf847fd508b907c2740
