### ISSUE TITLE
feature request: support EDNS0 RR

### ISSUE THREAD

**Issue by Sherlock-Holo** [LinkTed/dns-message-parser#3]
## The problems encountered

I try to add ECS info into the `Dns` to allow the dns server know where the query come from, but it seems [RData](https://docs.rs/dns-message-parser/0.3.0/dns_message_parser/enum.RData.html)::OPT has no value, the user can't add EDNS0 RR into the `Dns`

## Solution

it seems it is a good idea to add value into the `RData::OPT` so we can use EDNS0 :)

**Comment by LinkTed** [comment]
Hi @Sherlock-Holo,
Today I push a commit c561a18ee312a4b72e5c7407632fecf26459d4a0, which extends the OPT case. But it is not finished yet, because EDNS0 have encapsulated data types. Can you post an example packet as hex?

**Comment by Sherlock-Holo** [comment]
today I can't push am example because I don't have my dev environment….
I think I may can push am example next Monday🙈

**Comment by LinkTed** [comment]
Okay, no problem. 

I do not understand how exactly the address of ECS should be encoded. Truncated or truncated with zero padding, therefore it would be good if there is example.

Do you know, how to add an ECS entry to the zonefile of named?

**Comment by Sherlock-Holo** [comment]
I am also learning the edns0…sorry for that I can not help you

LinkTed <notifications@github.com> 于 2020年7月3日周五 01:00写道：

**Comment by Sherlock-Holo** [comment]
sorry for the late reply.

the wireshark show the dns request with ECS is

> ```
> 00000000  62 a6 01 20 00 01 00 00  00 00 00 01 03 77 77 77   b.. .... .....www
> 00000010  02 71 71 03 63 6f 6d 00  00 01 00 01 00 00 29 10   .qq.com. ......).
> 00000020  00 00 00 00 00 00 17 00  08 00 07 00 01 18 00 d0   ........ ........
> 00000030  43 de 00 0a 00 08 93 75  ca ee 8a f5 fa 5e         C......u .....^
> ```

does it can help you ?

**Comment by LinkTed** [comment]
Yes, it helps. Can you tell me which nameserver do you use?

**Comment by Sherlock-Holo** [comment]
I use 119.29.29.29

LinkTed <notifications@github.com> 于 2020年7月10日周五 02:55写道：

**Comment by LinkTed** [comment]
Okay, I will fix it at the end of the month.

**Comment by LinkTed** [comment]
Sorry that it took so long. I refactored the whole library. 

Now it supports EDNS0 (OPT):
* ECS [RFC 7871](https://tools.ietf.org/html/rfc7871)
* Cookie [RFC 7873](https://tools.ietf.org/html/rfc7873)

**Comment by Sherlock-Holo** [comment]
I read the new rr EDNS, it seems if I parse a dns response, i can get an edns struct but i can't get the source prefix, scope prefix or the address
how should i do to get these info？

**Comment by LinkTed** [comment]
A `EDNS` struct has an `ends_options` member, which contain an `ECS` struct. The `ECS` struct has the functions `get_prefix_length()`, `get_scope_prefix_length()` and `get_address()`.

**Comment by Sherlock-Holo** [comment]
in docs.rs it only have `get_prefix_length`
are the other method not release？

**Comment by LinkTed** [comment]
Sorry, I forgot to update the crate. I publish the version `0.4.2`.

**Comment by LinkTed** [comment]
@Sherlock-Holo can I close this issue?
