### ISSUE TITLE
Update docs for Questions import?

### ISSUE THREAD

**Issue by iankressin** [LinkTed/dns-message-parser#6]
I was getting the error `Question in the root help: a similar name exists in the module: question`
![image](https://user-images.githubusercontent.com/29215044/105483553-c710b280-5c88-11eb-8ece-e296b42d9009.png)

But I manage to fix it importing Question from `dns_message_parser::question::Question`

I can update the docs if it's the case

**Comment by LinkTed** [comment]
Did you use the example in the `README.md` file because if fix it today (343acce155b4442727b7ca8314ae9cc92d51a57d)?

**Comment by iankressin** [comment]
Yepp!!! That fixes the problem

**Comment by iankressin** [comment]
I'm getting another error when I try to create a new DomainName using the `try_from` associated method described in the docs.

`no function or associated item named **try_from** found for struct **DomainName** in the current scope: function or associated item not found in DomainName`

Code:

```
fn main() {
    let socket = UdpSocket::bind("127.0.0.1:8081").expect("Could not bind addr");
    let mut buf = [0 as u8; 512];
    let SERVER_NAME = DomainName::try_from("_drive.local.").unwrap();


    let (received, src_addr) = socket.recv_from(&mut buf)
        .expect("Didnt received any data");

    let packet = Bytes::copy_from_slice(&buf[..received]);
    let Dns { questions, .. }= Dns::decode(packet).unwrap();
    let Question { domain_name, .. }= questions.first().expect("No question was asked in this packet");

    if domain_name.eq(&SERVER_NAME) {
        println!("Same name");
    }

    socket.connect(src_addr).expect("Could not connect");

    socket.send(&"Hey".as_bytes()).expect("Could not send message");

    println!("{:#?}, {}", questions, src_addr);
}

```

**Comment by LinkTed** [comment]
Did you import the `TryFrom` trait? 

```rust
use std::convert::TryFrom;
```

**Comment by iankressin** [comment]
No didn't, my bad :(
Importing solved the problem

Thanks
